name: Run Tests

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false
        type: string
        options:
          - UI
          - API
      headless:
        description: 'Headless mode'
        required: false
        type: boolean
        default: true


jobs:
  autotests:
    name: Run tests and generate Allure Report
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4.1.1

      - name: Set up Java 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 21
          cache: 'maven'
          distribution: 'zulu'

      - name: Run test app
        id: runApp
        run: docker-compose up -d

      - name: Run Tests
        id: test
        run: |
          sleep 5
          mvn clean verify -Dgroups="${{inputs.tags}}" -D"selenide.headless=${{inputs.headless}}"
        continue-on-error: true

      - name: Setup Allure History
        uses: actions/checkout@v4.1.1
        if: steps.test.outcome == 'success' || 'failure'
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.9
        if: steps.test.outcome == 'success' || 'failure'
        with:
          allure_results: target/allure-results
          allure_history: allure-history

      - name: Publish Allure Report
        if: steps.test.outcome == 'success' || 'failure'
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
