name: Run Tests

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: true
        type: choice
        options:
          - UI
          - API
          - ALL
      headless:
        description: 'Headless mode'
        required: true
        type: boolean
        default: true


jobs:
  autotests:
    name: Run tests and generate Allure Report
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4.1.1


      - name: Set up Java 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 21
          cache: 'maven'
          distribution: 'zulu'

      - name: Set up chromedriver
        uses: nanasess/setup-chromedriver@v2